=begin
#WhatsApp chat API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for WatiClient::ContactsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactsApi' do
  before do
    # run before each test
    @api_instance = WatiClient::ContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactsApi' do
    it 'should create an instance of ContactsApi' do
      expect(@api_instance).to be_instance_of(WatiClient::ContactsApi)
    end
  end

  # unit tests for v1_add_contact_whatsapp_number_post
  # Add Contact
  # @param whatsapp_number WhatsApp Number with country code. Example, 85264318721
  # @param [Hash] opts the optional parameters
  # @option opts [NewContactModel] :new_contact_model Contact Attributes
  # @return [nil]
  describe 'v1_add_contact_whatsapp_number_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_get_contacts_get
  # Get Contacts List
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size Page Size
  # @option opts [Integer] :page_number Page Number
  # @option opts [String] :name Contact Name
  # @option opts [String] :attribute Attribute (parameters format : [{name: \&quot;name\&quot;, operator: \&quot;contain\&quot;, value: \&quot;test\&quot;}] )&lt;br /&gt;  Possible values for operator are contain, notContain, exist, notExist, &#x3D;&#x3D;, !&#x3D;, valid, invalid
  # @option opts [String] :created_date Created Date (YYYY-MM-DD or MM-DD-YYYY)
  # @return [nil]
  describe 'v1_get_contacts_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_update_contact_attributes_whatsapp_number_post
  # Update Contact Attributes
  # @param whatsapp_number WhatsApp Number with country code. Example, 85264318721
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateCustomParamsModel] :update_custom_params_model Contact Attributes
  # @return [nil]
  describe 'v1_update_contact_attributes_whatsapp_number_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
