=begin
#WhatsApp chat API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for WatiClient::InboxApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InboxApi' do
  before do
    # run before each test
    @api_instance = WatiClient::InboxApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InboxApi' do
    it 'should create an instance of InboxApi' do
      expect(@api_instance).to be_instance_of(WatiClient::InboxApi)
    end
  end

  # unit tests for v1_assign_operator_post
  # Assign User
  # @param email User Email
  # @param whatsapp_number WhatsApp Number with country code. Example, 85264318721
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_assign_operator_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
