=begin
#WhatsApp chat API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WatiClient::ButtonsMessageHeaderMedia
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WatiClient::ButtonsMessageHeaderMedia do
  let(:instance) { WatiClient::ButtonsMessageHeaderMedia.new }

  describe 'test an instance of ButtonsMessageHeaderMedia' do
    it 'should create an instance of ButtonsMessageHeaderMedia' do
      expect(instance).to be_instance_of(WatiClient::ButtonsMessageHeaderMedia)
    end
  end
  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "file_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
