=begin
#WhatsApp chat API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WatiClient::ButtonsMessageHeader
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WatiClient::ButtonsMessageHeader do
  let(:instance) { WatiClient::ButtonsMessageHeader.new }

  describe 'test an instance of ButtonsMessageHeader' do
    it 'should create an instance of ButtonsMessageHeader' do
      expect(instance).to be_instance_of(WatiClient::ButtonsMessageHeader)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "text"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "media"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
