=begin
#WhatsApp chat API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WatiClient::SourceType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WatiClient::SourceType do
  let(:instance) { WatiClient::SourceType.new }

  describe 'test an instance of SourceType' do
    it 'should create an instance of SourceType' do
      expect(instance).to be_instance_of(WatiClient::SourceType)
    end
  end
end
